### ISSUE TITLE
"mvn clean install" doesn't work out of the box 

### ISSUE THREAD

**Issue by pitometsyurii** [jonashackt/spring-boot-vuejs#121]
Once I've cloned the project "mvn clean install" fails running unit tests. Also running this command mvn --projects backend spring-boot:run doesn't work as well.

<img width="1096" alt="Screen Shot 2020-06-05 at 10 41 23" src="https://user-images.githubusercontent.com/4027685/83896034-27aea780-a719-11ea-9f84-c2be66857557.png">

**Comment by tellamon** [comment]
I've faced the exact same problem.

**Comment by Krysztokowski** [comment]
you need to build it first - that's why you cannot run "mvn --projects backend spring-boot:run". to build it quick with failing tests just add -DskipTests to your first cmd. it's bad style, but it's working

conclusion:
mvn clean install -DskipTests && mvn --projects backend spring-boot:run

**Comment by pitometsyurii** [comment]
The problem fixed for me once I've install `vie-cli`.

**Comment by winweb** [comment]
try to use RestAssured version 4.2.0

**Comment by tellamon** [comment]
@winweb That makes the tests succeeds. Thanks.
```
<rest-assured.version>4.2.0</rest-assured.version>
```

**Comment by jonashackt** [comment]
Sorry guys, the internal problem was a bug with `rest-assured`, which stopped to work as expected with version `4.3.0`. This wouldn't have been a problem, since renovate bot is configured to only merge new versions, if tests in CI servers succeed. But since GitHub and TravisCI changed there way of integration and TravisCI silently moved to travis-ci.com, the integration of the CI system was broken - but renovate didn't stop to automerge. 

With https://github.com/jonashackt/spring-boot-vuejs/pull/116 the problem is fixed again and a normal `mvn clean install` should work as expected.
