### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by Erdboden** [jonashackt/spring-boot-vuejs#19]
While hot reloading is enabled sometimes the route calls return 404. How can it be fixed? coming from php, it's really a struggle waiting all the time to recompile everything after some minor changes in the backend :(

**Comment by jonashackt** [comment]
Hi @Erdboden - so the frontend process of hot reloading with the webpack dev server works for you and now you want to also change things inside the Spring Boot backend - and these aren´t reloaded? Inside the backend´s [pom.xml](https://github.com/jonashackt/spring-boot-vuejs/blob/master/backend/pom.xml) the spring-boot-devtools should be in place to do the hot reloading of the backend. Depending on your IDE, this is triggering a fast restart of the backend. In IntelliJ you need to manually trigger a recompile in order to trigger this mechanism - at my Mac this is `cmd - F9`...

**Comment by Erdboden** [comment]
@jonashackt 

> now you want to also change things inside the Spring Boot backend - and these aren´t reloaded?
yes correct

> Inside the backend´s pom.xml the spring-boot-devtools should be in place to do the hot reloading of the backend. 
i already have that
So yes on windows I also use ctrl-f9 but sometimes REST controllers just fail after hot swap and return 404 error. after recompiling again everything works fine. 
Now i understand the problem is not related to this project so sorry for offtopic

**Comment by jonashackt** [comment]
Ok, so I close the ticket now :)
