### ISSUE TITLE
[Question] Deploy to servers like wildfly

### ISSUE THREAD

**Issue by CristianZatt** [jonashackt/spring-boot-vuejs#27]
Hi, I found this project to be the best ou there about spring and vue. I'm starting a project (for learning) based on yours, but I would not like to use heroku, I want to deploy to our private server (wildfly - war file).

If not ask too much, could you please add in the tutorial a section about how to deploy this way (local server) for who don't want to use heroku?

**Comment by jonashackt** [comment]
Hi @CristianZatt , there was already a question regarding the `.war` deployment of Spring Boot apps (which will be the same to this project, since everything is packed into a Spring Boot fat `.jar`): https://github.com/jonashackt/spring-boot-vuejs/issues/22 There´s some documentation linked - or give the https://spring.io/guides a try - there are very good resources!

**Comment by CristianZatt** [comment]
Got it, I did't know much about micro services, but I understand now how it works. There is no need for a server like wildfly. Thank you for the quick response.
